### ISSUE TITLE
有没有计划支持ie8+

### ISSUE THREAD

**Issue by liyang-love** [MonkSoul/Layx#4]
有部分旧的项目跑在xp上 只能搞个ie8装上，这个有没有计划支持IE8+的浏览器，IE10时win8上的基本上没什么人用win8   大部分要么win10要么win7，win7好像默认也是IE8

**Comment by monksoul** [comment]
目前不考虑支持IE8，不过有另外解决方案。我们也是做ERP的。目前国内很多人都是用360，qq或者百多浏览器，可以推荐客户用极速模式。如果客户非得用IE8，也可以，让客户安装Chrome Frame插件。这是谷歌提供的，让IE6-IE8采用Chrome内核渲染。
